on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Node.js dependencies
        run: npm install @actions/core @actions/github

      - name: run script
        run: node ./src/index.js
        env:
          INPUT_NAME: Fabi
